stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - post deploy

variables: 
  APP_BASE_URL: http://gitlab-tut.s3-website-eu-west-1.amazonaws.com/ 

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:16.16.0-alpine
  script:
    - echo "React Build started"
    - node -v
    - npm install
    - npm run build
    - echo "React Build completed"
  artifacts:
    paths:
      - build

test-job:
  stage: test
  image: node:16.16.0-alpine
  script:
    - echo "React Test started"
    - npm install -g serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"
    - echo "React Test completed"

deploy-to-s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.5.6
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "React Test started"
    - echo $CI_DEFAULT_BRANCH is a default branch of this project
    - echo $CI_COMMIT_REF_NAME branch is buildings
    - aws --version
    - aws s3 sync build s3://$S3_BUCKET --delete
    - echo "React Test completed"

production-test:
  stage: post deploy
  image: curlimages/curl
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "Post deploy test started"
    - curl $APP_BASE_URL | grep "React App"
    - echo "Post deploy test completed"