stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:16.16.0-alpine
  script:
    - echo "React Build started"
    - node -v
    - npm install
    - npm run build
    - echo "React Build completed"
  artifacts:
    paths:
      - build
