stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:16.16.0-alpine
  script:
    - echo "React Build started"
    - node -v
    - npm install
    - npm run build
    - echo "React Build completed"
  artifacts:
    paths:
      - build

test-job:
  stage: test
  image: node:16.16.0-alpine
  script:
    - echo "React Test started"
    - npm install -g serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"
    - echo "React Test completed"

deploy-to-s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.4
    entrypoint: [""]
  script:
    - echo "React Test started"
    - aws --version
    - echo "React Test completed"